export enum ActionTypes {
  LIKE_CREATE = 'LIKES/LIKES_REDUCER_CREATE',
  LIKE_CREATE_SUCCESS = 'LIKES/LIKES_REDUCER_CREATE_SUCCESS',
  LIKE_CREATE_FAILED = 'LIKES/LIKES_REDUCER_CREATE_FAILED',
  LIKE_GET_LIKE_BY_ADVERT_ID = 'LIKES/LIKES_REDUCER_GET_LIKES_BY_ADVERT_ID',
  LIKE_GET_LIKE_BY_ADVERT_ID_SUCCESS = 'LIKES/LIKES_REDUCER_GET_LIKES_BY_ADVERT_ID_SUCCESS',
  LIKE_GET_LIKE_BY_ADVERT_ID_FAILED = 'LIKES/LIKES_REDUCER_GET_LIKES_BY_ADVERT_ID_FAILED',
  LIKE_GET_SHARE_BY_ADVERT_ID = 'LIKES/LIKES_REDUCER_GET_SHARES_BY_ADVERT_ID',
  LIKE_GET_SHARE_BY_ADVERT_ID_SUCCESS = 'LIKES/LIKES_REDUCER_GET_SHARES_BY_ADVERT_ID_SUCCESS',
  LIKE_GET_SHARE_BY_ADVERT_ID_FAILED = 'LIKES/LIKES_REDUCER_GET_SHARES_BY_ADVERT_ID_FAILED',
}
