export enum ActionTypes {
  CREATE = 'ADVERT/CREATE',
  CREATE_SUCCESS = 'ADVERT/CREATE_SUCCESS',
  CREATE_FAILED = 'ADVERT/CREATE_FAILED',
  UPDATE = 'ADVERT/UPDATE',
  UPDATE_SUCCESS = 'ADVERT/UPDATE_SUCCESS',
  UPDATE_FAILED = 'ADVERT/UPDATE_FAILED',
  REMOVE = 'ADVERT/REMOVE',
  REMOVE_SUCCESS = 'ADVERT/REMOVE_SUCCESS',
  REMOVE_FAILED = 'ADVERT/REMOVE_FAILED',
  GET_BY_ID = 'ADVERT/GET_BY_ID',
  GET_BY_ID_SUCCESS = 'ADVERT/GET_BY_ID_SUCCESS',
  GET_BY_ID_FAILED = 'ADVERT/GET_BY_ID_FAILED',
}
