export enum ActionTypes {
  ADVERT_CREATE = 'ADVERT/CREATE',
  ADVERT_CREATE_SUCCESS = 'ADVERT/CREATE_SUCCESS',
  ADVERT_CREATE_FAILED = 'ADVERT/CREATE_FAILED',
  ADVERT_UPDATE = 'ADVERT/UPDATE',
  ADVERT_UPDATE_SUCCESS = 'ADVERT/UPDATE_SUCCESS',
  ADVERT_UPDATE_FAILED = 'ADVERT/UPDATE_FAILED',
  ADVERT_REMOVE = 'ADVERT/REMOVE',
  ADVERT_REMOVE_SUCCESS = 'ADVERT/REMOVE_SUCCESS',
  ADVERT_REMOVE_FAILED = 'ADVERT/REMOVE_FAILED',
  ADVERT_GET_BY_ID = 'ADVERT/GET_BY_ID',
  ADVERT_GET_BY_ID_SUCCESS = 'ADVERT/GET_BY_ID_SUCCESS',
  ADVERT_GET_BY_ID_FAILED = 'ADVERT/GET_BY_ID_FAILED',
}
