export enum ActionTypes {
  GET_COUNTRIES = 'COUNTRIES_API/COUNTRIES_API_GET_COUNTRIES',
  GET_COUNTRIES_SUCCESS = 'COUNTRIES_API/COUNTRIES_API_REDUCER_GET_COUNTRIES_SUCCESS',
  GET_COUNTRIES_FAILED = 'COUNTRIES_API/COUNTRIES_API_REDUCER_GET_COUNTRIES_FAILED',
  GET_STATES = 'COUNTRIES_API/COUNTRIES_API_GET_STATES',
  GET_STATES_SUCCESS = 'COUNTRIES_API/COUNTRIES_API_REDUCER_GET_STATES_SUCCESS',
  GET_STATES_FAILED = 'COUNTRIES_API/COUNTRIES_API_REDUCER_GET_STATES_FAILED',
  GET_CITIES = 'COUNTRIES_API/COUNTRIES_API_GET_CITIES',
  GET_CITIES_SUCCESS = 'COUNTRIES_API/COUNTRIES_API_REDUCER_GET_CITIES_SUCCESS',
  GET_CITIES_FAILED = 'COUNTRIES_API/COUNTRIES_API_REDUCER_GET_CITIES_FAILED',
}
