export enum ActionTypes {
  LOG_IN = 'AUTHORIZATION/LOG_IN',
  LOG_IN_SUCCESS = 'AUTHORIZATION/LOG_IN_SUCCESS',
  LOG_IN_FAILED = 'AUTHORIZATION/LOG_IN_FAILED',
  LOG_OUT = 'AUTHORIZATION/LOG_OUT',

  REGISTRATION = 'AUTHORIZATION/REGISTRATION',
  REGISTRATION_SUCCESS = 'AUTHORIZATION/REGISTRATION_SUCCESS',
  REGISTRATION_FAILED = 'AUTHORIZATION/REGISTRATION_FAILED',

  VERIFICATION = 'AUTHORIZATION/VERIFICATION',
  VERIFICATION_SUCCESS = 'AUTHORIZATION/VERIFICATION_SUCCESS',
  VERIFICATION_FAILED = 'AUTHORIZATION/VERIFICATION_FAILED',

  FORGOT_PASSWORD = 'AUTHORIZATION/FORGOT_PASSWORD',
  FORGOT_PASSWORD_SUCCESS = 'AUTHORIZATION/FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_CHANGE = 'AUTHORIZATION/FORGOT_PASSWORD_CHANGE',
  FORGOT_PASSWORD_FAILED = 'AUTHORIZATION/FORGOT_PASSWORD_FAILED',
}
