export enum PrivateRoutesPath {
  DASHBOARD = 'dashboard',
  DASHBOARD_MENTOR = '/mentor/:id',
  MENTOR = 'mentor',
  STUDENT = 'student',
  ADVERTS = 'adverts',
  LESSONS = 'lessons',
  LEARN_ITEMS = 'learn-items',
  USER = 'user',
  CATEGORIES = 'categories',
  SETTINGS = 'settings',
  IMAGES = 'images',
  USER_PROFILES = 'user-profiles',
  AUTH = 'auth',
  GET_BY_ID = '/:id',
  GET_ALL = '/all',
  COUNTRIES = 'countries',
  STATES = 'states',
  CITIES = 'cities',
  COUNTRY = '/:countryName/states',
  STATE = '/:stateName/cities',

  // TODO only for API
  POST_CREATE = '/create',
  POST_UPDATE = '/update/:id',
  POST_DELETE = '/delete/:id',
  GET_FIND_BY_ID = '/find-by-email',
  POST_LOGIN = '/login',
  POST_REGISTRY = '/registry',
  POST_VERIFY = '/verify/:code',
  POST_VERIFY_FE = '/verify/',
  POST_RESEND_VERIFY = '/resend-verification/:email',
  POST_FORGOT_PASSWORD = '/forgot-password/:email',
  POST_FORGOT_PASSWORD_FE = '/forgot-password',
  POST_RESET_PASSWORD = '/reset-password',
  POST_ADD_ADVERT = "POST_ADD_ADVERT"
}
