export enum PrivateRoutesPath {
  DASHBOARD = 'dashboard',
  DASHBOARD_MENTOR = '/mentor/:id',
  MENTOR = 'mentor',
  MENTORS = 'mentors',
  STUDENT = 'student',
  COURSES = 'courses',
  LESSONS = 'lessons',
  LEARN_ITEMS = 'learn-items',
  USER = 'user',
  CATEGORIES = 'categories',
  SETTINGS = 'settings',
  IMAGES = 'images',
  RATING = 'rating',
  LIKES = 'likes',
  SHARES = 'shares',
  USER_PROFILES = 'user-profiles',
  AUTH = 'auth',
  GET_BY_ID = '/:id',
  GET_ALL = '/all',
  COUNTRIES = 'countries',
  STATES = 'states',
  CITIES = 'cities',
  COUNTRY = '/:countryName/states',
  STATE = '/:stateName/cities',
  GET_BY_COURSE_ID = '/:courseid',
  FILTER = '/filter',
  COUNT = '/count',

  // TODO only for API
  POST_CREATE = '/create',
  POST_UPDATE = '/update',
  POST_DELETE = '/delete/:id',
  GET_FIND_BY_ID = '/find-by-email',
  POST_LOGIN = '/login',
  POST_REGISTRY = '/registry',
  POST_VERIFY = '/verify/:code',
  POST_VERIFY_FE = '/verify/',
  POST_RESEND_VERIFY = '/resend-verification/:email',
  POST_FORGOT_PASSWORD = '/forgot-password/:email',
  POST_FORGOT_PASSWORD_FE = '/forgot-password',
  POST_RESET_PASSWORD = '/reset-password',
  POST_ADD_COURSE = 'POST_ADD_COURSE',
  POST_ADD_STUDENT_TO_COURSE = '/addToCourse/:courseId',
  POST_REMOVE_STUDENT_FROM_COURSE = '/removeFromCourse/:courseId',
}
