export enum ActionTypes {
  SET_MESSAGE = 'SNACK_BAR_REDUCER/SET_MESSAGE',
  SET_MESSAGE_SUCCESS = 'SNACK_BAR_REDUCER/SET_MESSAGE_SUCCESS',
  SET_MESSAGE_FAILED = 'SNACK_BAR_REDUCER/SET_MESSAGE_FAILED'
}

export default ActionTypes;
