export enum ActionTypes {
  USER_PROFILE_GET = 'USER_PROFILE/GET',
  USER_PROFILE_GET_SUCCESS = 'USER_PROFILE/GET_SUCCESS',
  USER_PROFILE_GET_FAILED = 'USER_PROFILE/GET_FAILED',
  USER_PROFILE_UPDATE = 'USER_PROFILE/USER_PROFILE_UPDATE',
  USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE/USER_PROFILE_UPDATE_SUCCESS',
  USER_PROFILE_UPDATE_FAILED = 'USER_PROFILE/USER_PROFILE_UPDATE_FAILED',
}
