export enum ViewModels {
  USERS_VIEW = 'Users',
  PROJECTS_VIEW = 'Projects',
  COURSES_VIEW = 'Courses',
  LESSONS_VIEW = 'Lessons',
  LEARN_ITEMS_VIEW = 'LearnItems',
  LIKES_VIEW = 'Likes',
  RATINGS_VIEW = 'Ratings',
  CATEGORIES_VIEW = 'Categories',
  SETTINGS_VIEW = 'Settings',
  EMAIL_VERIFICATION = 'EmailVerification',
  FORGOTTEN_PASSWORD = 'ForgottenPassword',
  CONSENT_REGISTRY = 'ConsentRegistration',
  MENTORS = 'Mentors',
  STUDENTS = 'Students',
  PERMISSIONS_VIEW = 'Permissions',
  USER_PROFILES = 'UserProfiles',
  COUNTRIES_API_VIEW = 'CountriesApi',
}
