export enum ViewModels {
  USERS_VIEW = 'Users',
  PROJECTS_VIEW = 'Projects',
  ADVERTS_VIEW = 'Adverts',
  LESSONS_VIEW = 'Lessons',
  LEARN_ITEMS_VIEW = 'LearnItems',
  CATEGORIES_VIEW = 'Categories',
  SETTINGS_VIEW = 'Settings',
  EMAIL_VERIFICATION = 'EmailVerification',
  FORGOTTEN_PASSWORD = 'ForgottenPassword',
  CONSENT_REGISTRY = 'ConsentRegistration',
  MENTORS = 'Mentors',
  STUDENTS = 'Students',
  PERMISSIONS_VIEW = 'Permissions',
  USER_PROFILES = 'UserProfiles',
}
